apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe-deployment
  labels:
    app: tictactoe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tictactoe
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
        - name: tictactoe
          image: digdigdigdig/tictactoe:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: tictactoe-service
  labels:
    app: tictactoe
spec:
  type: LoadBalancer
  selector:
    app: tictactoe
  ports:
    - port: 80
      targetPort: 3333
      protocol: TCP

